Added capabilities for GPPA Google Sheets.
gravitywiz/gp-populate-anything-google-sheets pull request #4
Opened 2023-04-26 17:38 UTC by saifsultanc

## Context

⛑️ Ticket(s): https://secure.helpscout.net/conversation/2209746569/46609/

## Summary

This update adds the Members Plugin capabilities.

Here is how it works (< 100 seconds):
https://www.loom.com/share/0fa7f84572c246b19fb14bf81b88aea5

## Checklist

- [ ] Updated customer telling them that a fix/addition is in the works.
- [ ] Added/Improved Cypress tests or a note under _Summary_ why tests are not included in the PR.
- [ ] Added a link to this PR in the Help Scout ticket(s) in the form of a note
- [ ] Sent a [packed build](https://www.notion.so/gravitywiz/GWiz-Builder-de063e85494e4a8aace9994a3ef793f9#9de8bd246edb4d108324e5eb32b4d597) of this PR/branch for the customer to test.

2023-04-26 18:09 UTC, claygriffiths requested changes
Can you make this PR match how it was done in https://github.com/gravitywiz/gravityforms-openai/pull/3 including the title/commit message?

2023-05-02 20:14 UTC, claygriffiths requested changes

2023-05-02 20:14 UTC, claygriffiths commented on class-gppa-google-sheets.php
> +		'gp-populate-anything-google-sheets_results',
I think you can remove `results` from here. Apologies if another PR I pointed to has that in it

2023-07-19 16:09 UTC, saifsultanc commented
as discussed with @clay , since there is a lack of response from the customer closing it for now.

2023-07-19 16:09 UTC, closed without merging